letters = {
	'A':{'freq': 9,'val': 1},
	'B':{'freq': 2,'val': 3},
	'C':{'freq': 2,'val': 3},
	'D':{'freq': 4,'val': 2},
	'E':{'freq':12,'val': 1},
	'F':{'freq': 2,'val': 4},
	'G':{'freq': 3,'val': 2},
	'H':{'freq': 2,'val': 4},
	'I':{'freq': 9,'val': 1},
	'J':{'freq': 1,'val': 8},
	'K':{'freq': 1,'val': 5},
	'L':{'freq': 4,'val': 1},
	'M':{'freq': 2,'val': 3},
	'N':{'freq': 6,'val': 1},
	'O':{'freq': 8,'val': 1},
	'P':{'freq': 2,'val': 3},
	'Q':{'freq': 1,'val':10},
	'R':{'freq': 6,'val': 1},
	'S':{'freq': 4,'val': 1},
	'T':{'freq': 6,'val': 1},
	'U':{'freq': 4,'val': 1},
	'V':{'freq': 2,'val': 4},
	'W':{'freq': 2,'val': 4},
	'X':{'freq': 1,'val': 8},
	'Y':{'freq': 2,'val': 4},
	'Z':{'freq': 1,'val':10},
	'?':{'freq': 2,'val': 0},
}